export enum ErrorMessages {
  CLERK_INVITATION_SENT_ERROR = "Clerk error sending invitation to new user",
  CLERK_ORG_CREATE_ERROR = "Error creating Clerk organization",
  CLERK_ORG_INVITATION_ERROR = "Clerk error inviting user to organization",
  CLERK_ORG_UPDATE_MEMBERSHIP = "Clerk error updating organization membership",
  CLERK_ORG_UPDATE_NAME = "Clerk error updating organization name",
  CLERK_ORG_REVOKE_ERROR = "Cler error revoking invitation",
  CLERK_UPDATE_NAME = "Clerk error updating name",
  COMPANY_DB_CREATE_ERROR = "Database error creating company",
  COMPANY_DB_QUERY_BY_ID = "DB error query company by Id",
  COMPANY_DB_QUERY_BY_CLERK_ORG_ID = "DB error query company by clerk org Id",
  COMPANY_DB_QUERY_BY_SLUG = "DB error query company by slug",
  COMPANY_INACTIVE = "Company is inactive",
  COMPANY_NOT_FOUND = "Company not found",
  CONTEXT_USE_TEAM_PROVIDER = "useTeamContext must be used within a TeamProvider",
  CONTEXT_SLUG_PROVER = "useSlugContext must be used within a SlugProvider",
  CUSTOMER_EXISTS = "Customer already exists.",
  CUSTOMER_DB_CREATE_ERROR = "Database error creating user",
  CUSTOMER_DB_QUERY_BY_EMAIL_ERROR = "Database error query customer by email",
  CUSTOMER_DB_UPDATE_ERROR = "Database error updating user",
  ENV_CLERK_SECRET_KEY_NOT_SET = "ENV_CLERK_SECRET_KEY_NOT_SET is not set. Please configure it in your environment variables.",
  ENV_NEXT_PUBLIC_CONVEX_UR_NOT_SET = "NEXT_PUBLIC_CONVEX_URL is not set. Please configure it in your environment variables.",
  FOBIDDEN_COMPANY = "User does not belong to company",
  MIDDLEWARE_REDIRECT_HOME = "Middleware error redirect user for home route",
  USER_DB_QUERY_BY_EMAIL = "Database error querying user by email",
  USER_DB_QUERY_BY_ID = "Database error querying user by id",
  USER_DB_CREATE = "Database error creating user",
  USER_DB_UPDATE = "DB error updating user",
  USER_EXISTS = "User already exists",
  USER_FORBIDDEN_PERMISSION = "You do not have permission to perform this action.",
  USER_INACTIVE = "User is inactive",
  USER_NO_COMPANY = "User does not have a company",
  USER_NOT_AUTHENTICATED = "User is not authenticated",
  USER_NOT_CUSTOMER = "User is not a customer",
  USER_NOT_FOUND = "User not found",
  USER_WITH_EMAIL_EXISTS = "User with email exists",
  GENERIC_ERROR = "An unexpected error occurred. Please try again later.",
  INVALID_EMAIL = "Please enter a valid email address.",
  INVITATION_ALREADY_ACCEPTED = "Invitation already accepted. It cannot be revoked",
  INVITATION_ALREADY_REVOKED = "Invitation already revoked",
  INVITATION_DB_CREATE = "DB error creating an invitation",
  INVITATION_DB_QUERY_BY_EMAIL = "DB error query invitation by email",
  INVITATION_DB_QUERY_BY_ID = "DB error query invitation by id",
  INVITATION_DB_UPDATE = "DB error updating invitation status",
  INVITATION_NOT_FOUND = "Invitation not found",
}

export enum FrontEndErrorMessages {
  EMAIL_INVALID = "Invalid email format.",
  EMAIL_REQUIRED = "Email is required.",
  HOURLY_RATE_INVALID = "Invalid hourly rate.",
  INVITE_USER_ERROR = "Error occured inviting user.",
  GENERIC = "An unexpected error occurred. Please try again later.",
  ROLE_INVALID = "Invalid role.",
}
